version: "3.0"

services:
# faas-gateway:
#   build:
#     context: ./faas-gateway
#   ports:
#     - "8080:80"
#   volumes:
#     - /var/run/docker.sock:/var/run/docker.sock
#     - ./faas-gateway:/go/src/github.com/modfin/faas-scaffold/faas-gateway

 multiply:
   build:
     context: ./multiply
   labels:
     - "faas.name=multiply"
     - "faas.port=8080"
   ports:
     - "8080:9000"
   volumes:
     - ./multiply:/go/src/github.com/modfin/faas-scaffold/multiply