version: "3.0"

services:
 faas-gateway:
   image: faas-scaffold_faas-gateway:latest
   build:
     context: ./faas-gateway
   deploy:
    placement:
      constraints:
        - node.role == manager
   ports:
     - "8081:8081"
   volumes:
     -  /var/run/docker.sock:/var/run/docker.sock
   networks:
     - faas
 multiply:
   image: faas-scaffold_math:latest
   deploy:
      replicas: 2
   environment:
     - mode=multiply
   build:
     context: ./math
   labels:
     - "faas.name=multiply"
     - "faas.port=8082"
   networks:
     - faas
 add:
   image: faas-scaffold_math:latest
   deploy:
     replicas: 2
   environment:
     - mode=add
   build:
     context: ./math
   labels:
     - "faas.name=add"
     - "faas.port=8082"
   networks:
     - faas

networks:
  faas:
    driver: overlay