version: "3.0"

services:
 faas-gateway:
   image: faas-scaffold_faas-gateway:latest
   build:
     context: ./faas-gateway
   ports:
     - "8081:8081"
   volumes:
     -  /var/run/docker.sock:/var/run/docker.sock
   networks:
     - faas
 multiply:
   image: faas-scaffold_multiply:latest
   deploy:
      replicas: 2
   build:
     context: ./multiply
   labels:
     - "faas.name=multiply"
     - "faas.port=8082"
   networks:
     - faas

networks:
  faas:
    driver: overlay